In [ ]:
# python list
# list comprehension
# array module (import lib array)
# numpy array  
#       zeos
#       nes
#      full
#      eye
#      arange
#      eshape
#       indexing

In [118]:
import numpy as np

In [5]:
np.__version__

'1.26.4'

In [7]:
get_ipython().run_line_magic('pinfo', 'np.zeros')

Docstring:
zeros(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, filled with zeros.

Parameters
----------
shape : int or tuple of ints
    Shape of the new array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    The desired data-type for the array, e.g., `numpy.int8`.  Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of zeros with the given shape, dtype, and order.

See Al

In [9]:
help(len)

Help on built-in function len in module builtins:

len(obj, /)
    Return the number of items in a container.



In [11]:
arr = np.arange(0,100)

In [15]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [21]:
np.arange(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [23]:
get_ipython().run_line_magic('pinfo', 'np.arange')


Docstring:
arange([start,] stop[, step,], dtype=None, *, like=None)

Return evenly spaced values within a given interval.

``arange`` can be called with a varying number of positional arguments:

* ``arange(stop)``: Values are generated within the half-open interval
  ``[0, stop)`` (in other words, the interval including `start` but
  excluding `stop`).
* ``arange(start, stop)``: Values are generated within the half-open
  interval ``[start, stop)``.
* ``arange(start, stop, step)`` Values are generated within the half-open
  interval ``[start, stop)``, with spacing between values given by
  ``step``.

For integer arguments the function is roughly equivalent to the Python
built-in :py:class:`range`, but returns an ndarray rather than a ``range``
instance.

When using a non-integer step, such as 0.1, it is often better to use
`numpy.linspace`.

See the Warning sections below for more information.

Parameters
----------
start : integer or real, optional
    Start of interval.  The interva

In [25]:
np.arange(0,100,4)

array([ 0,  4,  8, 12, 16, 20, 24, 28, 32, 36, 40, 44, 48, 52, 56, 60, 64,
       68, 72, 76, 80, 84, 88, 92, 96])

In [27]:
np.arange(-78,78)

array([-78, -77, -76, -75, -74, -73, -72, -71, -70, -69, -68, -67, -66,
       -65, -64, -63, -62, -61, -60, -59, -58, -57, -56, -55, -54, -53,
       -52, -51, -50, -49, -48, -47, -46, -45, -44, -43, -42, -41, -40,
       -39, -38, -37, -36, -35, -34, -33, -32, -31, -30, -29, -28, -27,
       -26, -25, -24, -23, -22, -21, -20, -19, -18, -17, -16, -15, -14,
       -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,  -3,  -2,  -1,
         0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77])

In [29]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [31]:
# Difference between List and Numpy Array.
"In list, we can store different datatype elements. And in Numpy Array we can only store any 1 datatype elements."
"Lists take time computing as it has multiple datatypes to deal with. Array computes faster as it only has to compute single datatype."

'Lists take time computing as it has multiple datatypes to deal with. Array computes faster as it only has to compute single datatype.'

In [33]:
l2 = [ x for x in range(0,10)]

In [35]:
l2

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [37]:
l3 = [str(x) for x in l2]

In [39]:
l3

['0', '1', '2', '3', '4', '5', '6', '7', '8', '9']

In [41]:
l4 = [x**2 for x in l2]

In [43]:
l4

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81]

In [45]:
type(l4)


list

In [47]:
import array

In [49]:
help(array)

Help on built-in module array:

NAME
    array

DESCRIPTION
    This module defines an object type which can efficiently represent
    an array of basic values: characters, integers, floating point
    numbers.  Arrays are sequence types and behave very much like lists,
    except that the type of objects stored in them is constrained.

CLASSES
    builtins.object
        array

    ArrayType = class array(builtins.object)
     |  array(typecode [, initializer]) -> array
     |
     |  Return a new array whose items are restricted by typecode, and
     |  initialized from the optional initializer value, which must be a list,
     |  string or iterable over elements of the appropriate type.
     |
     |  Arrays represent basic values and behave very much like lists, except
     |  the type of objects stored in them is constrained. The type is specified
     |  at object creation time by using a type code, which is a single character.
     |  The following type codes are defined:
     |

In [51]:
arr = array.array('i', l2)

In [53]:
arr

array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
type(arr)

array.array

In [57]:
arr1 = array.array('i',[x**2 for x in l2])

In [59]:
arr1

array('i', [0, 1, 4, 9, 16, 25, 36, 49, 64, 81])

In [61]:
np.array(l2)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [63]:
np.array([x + 3 for x in range(0,10)])

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [65]:
np.array([x - 3 for x in range(0,10)])

array([-3, -2, -1,  0,  1,  2,  3,  4,  5,  6])

In [67]:
np.array([1,2,3,4,5],dtype='float')

array([1., 2., 3., 4., 5.])

In [69]:
np.array([1,2,3,4,5],dtype=str)

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [71]:
np.array([1,2,3,4,5],dtype=np.float64)

array([1., 2., 3., 4., 5.])

In [73]:
l2d = [[1,2,3],[4,5,6]]

In [75]:
l2d

[[1, 2, 3], [4, 5, 6]]

In [77]:
lc2d = [range(i,i+3) for i in [1,4,7]]

In [79]:
lc2d

[range(1, 4), range(4, 7), range(7, 10)]

In [81]:
np.array(lc2d)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [85]:
np.zeros([2,2])

array([[0., 0.],
       [0., 0.]])

In [87]:
np.zeros([3,4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [89]:
np.ones(10,dtype=int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [91]:
np.ones([2,2],dtype=int)

array([[1, 1],
       [1, 1]])

In [93]:
arr = np.ones([10,10], dtype = int)

In [95]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [97]:
arr[4:6,4:6] = 1

In [99]:
arr

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [101]:
arr = np.ones([3,3],dtype = int)

In [107]:
3.1*arr

array([[3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1],
       [3.1, 3.1, 3.1]])

In [109]:
np.full((3,4),3.14)

array([[3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14]])

In [111]:
arr = np.eye(3,dtype = int)

In [113]:
np.transpose(arr)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [115]:
ar1 = np.ones([6,6], dtype = int)

In [117]:
64*ar1

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [119]:
np.full([6,6], 64, dtype = int)

array([[64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64],
       [64, 64, 64, 64, 64, 64]])

In [121]:
#linspace function => Linearly spaced elements.

np.linspace(0,1,5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [123]:
np.linspace(0,100,5)

array([  0.,  25.,  50.,  75., 100.])

In [125]:
import numpy as np

In [127]:
#shallow copy
a=np.arange(1,10).reshape(3,3)

In [129]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [131]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [133]:
#deep copy
da=a[:2,:2].copy()

In [135]:
da

array([[1, 2],
       [4, 5]])

In [137]:
a[0,0]=11

In [139]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [141]:
da

array([[1, 2],
       [4, 5]])

In [143]:
da[1,1]=5

In [145]:
a

array([[11,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [147]:
c=np.arange(1,5)
c

array([1, 2, 3, 4])

In [149]:
c.reshape(2,2)

array([[1, 2],
       [3, 4]])

In [151]:
ar=np.arange(1,10).reshape(3,3)
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [153]:
import numpy as np

# Shallow & Deep Copy
# Reshape ~ Flatten , Reval
# Concatenation

In [158]:
arr1 = np.random.randint(0,18,(6,6))

In [160]:
arr1

array([[16,  3, 15, 15, 10,  7],
       [12, 11,  8,  4, 12, 15],
       [14, 13, 15, 10,  4,  4],
       [ 5,  5,  3,  3,  5, 12],
       [ 9,  3,  0, 13,  8,  4],
       [ 8,  3, 14,  3, 10, 14]])

In [162]:
arr1[0:3,0:3]

array([[16,  3, 15],
       [12, 11,  8],
       [14, 13, 15]])

In [164]:
arr1[0:3,1:3]

array([[ 3, 15],
       [11,  8],
       [13, 15]])

In [166]:
arr1[2:5,3:5]

array([[10,  4],
       [ 3,  5],
       [13,  8]])

In [168]:
arr1[::,::]

array([[16,  3, 15, 15, 10,  7],
       [12, 11,  8,  4, 12, 15],
       [14, 13, 15, 10,  4,  4],
       [ 5,  5,  3,  3,  5, 12],
       [ 9,  3,  0, 13,  8,  4],
       [ 8,  3, 14,  3, 10, 14]])

In [170]:
arr1[::,::]

array([[16,  3, 15, 15, 10,  7],
       [12, 11,  8,  4, 12, 15],
       [14, 13, 15, 10,  4,  4],
       [ 5,  5,  3,  3,  5, 12],
       [ 9,  3,  0, 13,  8,  4],
       [ 8,  3, 14,  3, 10, 14]])

In [172]:
arr1[::2,::]

array([[16,  3, 15, 15, 10,  7],
       [14, 13, 15, 10,  4,  4],
       [ 9,  3,  0, 13,  8,  4]])

In [174]:
arr1[::,::2]

array([[16, 15, 10],
       [12,  8, 12],
       [14, 15,  4],
       [ 5,  3,  5],
       [ 9,  0,  8],
       [ 8, 14, 10]])

In [176]:
arr1[::-1,::]

array([[ 8,  3, 14,  3, 10, 14],
       [ 9,  3,  0, 13,  8,  4],
       [ 5,  5,  3,  3,  5, 12],
       [14, 13, 15, 10,  4,  4],
       [12, 11,  8,  4, 12, 15],
       [16,  3, 15, 15, 10,  7]])

In [178]:
arr1[::-1,::-1]

array([[14, 10,  3, 14,  3,  8],
       [ 4,  8, 13,  0,  3,  9],
       [12,  5,  3,  3,  5,  5],
       [ 4,  4, 10, 15, 13, 14],
       [15, 12,  4,  8, 11, 12],
       [ 7, 10, 15, 15,  3, 16]])

In [180]:
matrix1 = np.eye(4)

In [182]:
matrix2 = matrix1 + 4

In [184]:
print(matrix2)

[[5. 4. 4. 4.]
 [4. 5. 4. 4.]
 [4. 4. 5. 4.]
 [4. 4. 4. 5.]]


# Shallow & Deep Copy

In [191]:
a = np.arange(1,10).reshape(3, 3)

In [193]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [195]:
a[1:,1:3]

array([[5, 6],
       [8, 9]])

In [197]:
#Shallow Copy
sa=a[1:3,1:3]
sa

array([[5, 6],
       [8, 9]])

In [199]:
sa[1,1]=19
sa

array([[ 5,  6],
       [ 8, 19]])

In [201]:
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8, 19]])

In [203]:
a[1,2]=16

In [205]:
sa

array([[ 5, 16],
       [ 8, 19]])

In [207]:
a

array([[ 1,  2,  3],
       [ 4,  5, 16],
       [ 7,  8, 19]])

In [209]:
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [211]:
#Deep Copy
da = a[:2,:2].copy()
da

array([[1, 2],
       [4, 5]])

In [213]:
a[0,0]=11
a

array([[11,  2,  3],
       [ 4,  5, 16],
       [ 7,  8, 19]])

In [215]:
da

array([[1, 2],
       [4, 5]])

In [217]:
ar = np.array([1, 2, 3])

In [219]:
ar

array([1, 2, 3])

In [221]:
ar.reshape(3,1)

array([[1],
       [2],
       [3]])

In [223]:
ar1 = np.arange(0,9)
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [225]:
ar1.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [227]:
ar1.reshape(1,9)

array([[0, 1, 2, 3, 4, 5, 6, 7, 8]])

In [229]:
ar1.ravel?

Docstring:
a.ravel([order])

Return a flattened array.

Refer to `numpy.ravel` for full documentation.

See Also
--------
numpy.ravel : equivalent function

ndarray.flat : a flat iterator on the array.
Type:      builtin_function_or_method

In [231]:
ar1.flatten?

Docstring:
a.flatten(order='C')

Return a copy of the array collapsed into one dimension.

Parameters
----------
order : {'C', 'F', 'A', 'K'}, optional
    'C' means to flatten in row-major (C-style) order.
    'F' means to flatten in column-major (Fortran-
    style) order. 'A' means to flatten in column-major
    order if `a` is Fortran *contiguous* in memory,
    row-major order otherwise. 'K' means to flatten
    `a` in the order the elements occur in memory.
    The default is 'C'.

Returns
-------
y : ndarray
    A copy of the input array, flattened to one dimension.

See Also
--------
ravel : Return a flattened array.
flat : A 1-D flat iterator over the array.

Examples
--------
>>> a = np.array([[1,2], [3,4]])
>>> a.flatten()
array([1, 2, 3, 4])
>>> a.flatten('F')
array([1, 3, 2, 4])
Type:      builtin_function_or_method

In [233]:
ar1.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [235]:
ar1 = ar1.flatten()

In [239]:
ar1

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [241]:
ar1[:,np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

# Concatenation , Joining Of Two Arrays

In [246]:
np.concatenate?

Call signature:  np.concatenate(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <built-in function concatenate>
Docstring:      
concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")

Join a sequence of arrays along an existing axis.

Parameters
----------
a1, a2, ... : sequence of array_like
    The arrays must have the same shape, except in the dimension
    corresponding to `axis` (the first, by default).
axis : int, optional
    The axis along which the arrays will be joined.  If axis is None,
    arrays are flattened before use.  Default is 0.
out : ndarray, optional
    If provided, the destination to place the result. The shape must be
    correct, matching that of what concatenate would have returned if no
    out argument were specified.
dtype : str or dtype
    If provided, the destination array will have this dtype. Cannot be
    provided together with `out`.

    .. versionadded:: 1.20.0

casting : {'no', 'equiv', 'safe', 

# stack : Stack a sequence of arrays along a new axis.

block : Assemble arrays from blocks.
hstack : Stack arrays in sequence horizontally (column wise).
vstack : Stack arrays in sequence vertically (row wise).
dstack : Stack arrays in sequence depth wise (along third dimension).
column_stack : Stack 1-D arrays as columns into a 2-D array.

In [249]:
da

array([[1, 2],
       [4, 5]])

In [251]:
sa

array([[ 5, 16],
       [ 8, 19]])

In [253]:
np.concatenate([sa,da])

array([[ 5, 16],
       [ 8, 19],
       [ 1,  2],
       [ 4,  5]])

In [260]:
ca = np.concatenate([sa,da], axis = 1)
ca
# axis to specify row or column

array([[ 5, 16,  1,  2],
       [ 8, 19,  4,  5]])

# Axis To Specify Row 0 / Column 1

In [268]:
np.concatenate([ca,ar1])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [270]:
a1 = np.array([[1,1,1,1]])
a1

array([[1, 1, 1, 1]])

# To Concatenate For Rows = No. Of Columns Same
# For Columns = No. Of Rows Same


In [276]:
np.concatenate([ar1,c])

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 1, 2, 3, 4])

In [280]:
np.concatenate([ar,c],axis=0)
# axis to specify row 0/ column 1

array([1, 2, 3, 1, 2, 3, 4])

In [282]:
np.vstack?

Signature:       np.vstack(tup, *, dtype=None, casting='same_kind')
Call signature:  np.vstack(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vstack at 0x000001DAD4B0DE40>
File:            c:\users\siya\.conda\lib\site-packages\numpy\core\shape_base.py
Docstring:      
Stack arrays in sequence vertically (row wise).

This is equivalent to concatenation along the first axis after 1-D arrays
of shape `(N,)` have been reshaped to `(1,N)`. Rebuilds arrays divided by
`vsplit`.

This function makes most sense for arrays with up to 3 dimensions. For
instance, for pixel-data with a height (first axis), width (second axis),
and r/g/b channels (third axis). The functions `concatenate`, `stack` and
`block` provide more general stacking and concatenation operations.

``np.row_stack`` is an alias for `vstack`. They are the same function.

Parameters
----------
tup : sequence of ndarrays
    The arrays must have the same shape along all but the first axis.
    

In [298]:
#Stack arrays in sequence vertically (row wise)
a=np.arange(9,18).reshape(3,3)

In [302]:
ad=np.arange(1,4)
ad=ad[:,np.newaxis]    

In [304]:
ap=np.arange(1,4)


In [306]:
np.vstack((a,ap))

array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17],
       [ 1,  2,  3]])

In [308]:
np.hstack((a,ad))

array([[ 9, 10, 11,  1],
       [12, 13, 14,  2],
       [15, 16, 17,  3]])

In [312]:
np.split?


Signature:       np.split(ary, indices_or_sections, axis=0)
Call signature:  np.split(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function split at 0x000001DAD4C40D60>
File:            c:\users\siya\.conda\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays as views into `ary`.

Parameters
----------
ary : ndarray
    Array to be divided into sub-arrays.
indices_or_sections : int or 1-D array
    If `indices_or_sections` is an integer, N, the array will be divided
    into N equal arrays along `axis`.  If such a split is not possible,
    an error is raised.

    If `indices_or_sections` is a 1-D array of sorted integers, the entries
    indicate where along `axis` the array is split.  For example,
    ``[2, 3]`` would, for ``axis=0``, result in

      - ary[:2]
      - ary[2:3]
      - ary[3:]

    If an index exceeds the dimension of the array along `axis`,
    an empty sub-array is returned corresponding

In [320]:
np.hsplit?

Signature:       np.hsplit(ary, indices_or_sections)
Call signature:  np.hsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function hsplit at 0x000001DAD4C40EA0>
File:            c:\users\siya\.conda\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays horizontally (column-wise).

Please refer to the `split` documentation.  `hsplit` is equivalent
to `split` with ``axis=1``, the array is always split along the second
axis except for 1-D arrays, where it is split at ``axis=0``.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.hsplit(x, 2)
[array([[  0.,   1.],
       [  4.,   5.],
       [  8.,   9.],
       [12.,  13.]]),
 array([[  2.,   3.],
       [  6.,   7.],
       [10.,  11

In [316]:
np.vsplit?


Signature:       np.vsplit(ary, indices_or_sections)
Call signature:  np.vsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function vsplit at 0x000001DAD4C40F40>
File:            c:\users\siya\.conda\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split an array into multiple sub-arrays vertically (row-wise).

Please refer to the ``split`` documentation.  ``vsplit`` is equivalent
to ``split`` with `axis=0` (default), the array is always split along the
first axis regardless of the array dimension.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(4, 4)
>>> x
array([[ 0.,   1.,   2.,   3.],
       [ 4.,   5.,   6.,   7.],
       [ 8.,   9.,  10.,  11.],
       [12.,  13.,  14.,  15.]])
>>> np.vsplit(x, 2)
[array([[0., 1., 2., 3.],
       [4., 5., 6., 7.]]), array([[ 8.,  9., 10., 11.],
       [12., 13., 14., 15.]])]
>>> np.vsplit(x, np.array([3, 6]))
[array([[ 

In [324]:
np.dsplit?

Signature:       np.dsplit(ary, indices_or_sections)
Call signature:  np.dsplit(*args, **kwargs)
Type:            _ArrayFunctionDispatcher
String form:     <function dsplit at 0x000001DAD4C40FE0>
File:            c:\users\siya\.conda\lib\site-packages\numpy\lib\shape_base.py
Docstring:      
Split array into multiple sub-arrays along the 3rd axis (depth).

Please refer to the `split` documentation.  `dsplit` is equivalent
to `split` with ``axis=2``, the array is always split along the third
axis provided the array dimension is greater than or equal to 3.

See Also
--------
split : Split an array into multiple sub-arrays of equal size.

Examples
--------
>>> x = np.arange(16.0).reshape(2, 2, 4)
>>> x
array([[[ 0.,   1.,   2.,   3.],
        [ 4.,   5.,   6.,   7.]],
       [[ 8.,   9.,  10.,  11.],
        [12.,  13.,  14.,  15.]]])
>>> np.dsplit(x, 2)
[array([[[ 0.,  1.],
        [ 4.,  5.]],
       [[ 8.,  9.],
        [12., 13.]]]), array([[[ 2.,  3.],
        [ 6.,  7.]],
       [[1

In [336]:
A=np.array([1,2,3,4,5,6])
A

array([1, 2, 3, 4, 5, 6])

In [338]:
#Number split in a range 
np.split(A,[2,4])

[array([1, 2]), array([3, 4]), array([5, 6])]

In [344]:
np.hsplit(a,[1,2])

[array([1]), array([2]), array([3, 4, 5, 6])]

In [354]:
np.hsplit(a,[1,2])


[array([1]), array([2]), array([3, 4, 5, 6])]

In [358]:
b=np.arange(1,28).reshape(3,3,3)
b

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [362]:
np.dsplit(b,3)

[array([[[ 1],
         [ 4],
         [ 7]],
 
        [[10],
         [13],
         [16]],
 
        [[19],
         [22],
         [25]]]),
 array([[[ 2],
         [ 5],
         [ 8]],
 
        [[11],
         [14],
         [17]],
 
        [[20],
         [23],
         [26]]]),
 array([[[ 3],
         [ 6],
         [ 9]],
 
        [[12],
         [15],
         [18]],
 
        [[21],
         [24],
         [27]]])]

In [364]:
import numpy as np

In [368]:
c=np.arange(1,10).reshape(3,3)
c

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [370]:
np.sum(c)

45

In [372]:
np.sum(c,axis=0)


array([12, 15, 18])

In [376]:
np.sum(c,axis=1)

array([ 6, 15, 24])

In [378]:
np.min(r)

1

In [380]:
type(c)

numpy.ndarray

In [382]:
np.max(c)

9

In [384]:
# Index of min
np.argmin(r)

0

In [386]:
# Index of max
np.argmax(r)

8

In [388]:
np.abs(c)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [392]:
np.var(c)

6.666666666666667

In [394]:
np.std(c)

2.581988897471611

In [396]:
np.median(c)

5.0

In [398]:
np.prod(c)

362880

In [400]:
import numpy as np

In [402]:
np.empty?

Docstring:
empty(shape, dtype=float, order='C', *, like=None)

Return a new array of given shape and type, without initializing entries.

Parameters
----------
shape : int or tuple of int
    Shape of the empty array, e.g., ``(2, 3)`` or ``2``.
dtype : data-type, optional
    Desired output data-type for the array, e.g, `numpy.int8`. Default is
    `numpy.float64`.
order : {'C', 'F'}, optional, default: 'C'
    Whether to store multi-dimensional data in row-major
    (C-style) or column-major (Fortran-style) order in
    memory.
like : array_like, optional
    Reference object to allow the creation of arrays which are not
    NumPy arrays. If an array-like passed in as ``like`` supports
    the ``__array_function__`` protocol, the result will be defined
    by it. In this case, it ensures the creation of an array object
    compatible with that passed in via this argument.

    .. versionadded:: 1.20.0

Returns
-------
out : ndarray
    Array of uninitialized (arbitrary) data of the gi

In [81]:
import numpy as np

In [83]:
arr1 = np.random.randint(0,24,10)
arr1

array([23, 16, 12,  8, 18,  0,  0, 14, 23,  2])

In [85]:
arr2 = np.random.random((2,2))
arr2

array([[0.39668553, 0.18631223],
       [0.4246705 , 0.51458314]])

In [87]:
arr3 = np.random.random((3,3))
arr3

array([[0.69285081, 0.54599293, 0.97344661],
       [0.71015857, 0.03232925, 0.7519085 ],
       [0.67573214, 0.71462745, 0.83051715]])

In [91]:
arr1.dtype

dtype('int32')

In [93]:
arr2.dtype

dtype('float64')

In [95]:
arr3.dtype

dtype('float64')

In [97]:
arr1.shape

(10,)

In [99]:
arr2.shape

(2, 2)

In [101]:
arr3.shape

(3, 3)

In [105]:
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [107]:
np.ones((2,2))

array([[1., 1.],
       [1., 1.]])

In [110]:
np.eye(5,5,dtype=int)

array([[1, 0, 0, 0, 0],
       [0, 1, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 1]])

# Assignment 1

1. Import Numpy as np 

2. Create an array of 10 zeros 

3. Create an array of 10 ones 

4. Create an array of the integers from 10 to 50 

5. Create an array of all the even integers from 10 to 50 

6. Create a 3x3 matrix with values ranging from 0 to 8 

7. Create a 3x3 identity matrix 

8. Use NumPy to generate a random number between 0 to 1 

9. Use Numpy to generate an array of 25 random numbers sampled from a standard normal distribution 

10. Create a matrix of 10x10 matrix of linearly spaced elements from 0.01 to 1 

11. Create an array of 20 linearly spaced points between 0 and 1 

12. Create a 5x5 matrix as array([[ 1, 2, 3, 4, 5], [ 6, 7, 8, 9, 10], 
 [11, 12, 13, 14, 15], 
 [16, 17, 18, 19, 20], 
[21, 22, 23, 24, 25]]) Find 
 following using slicing 

a. array([[12, 13, 14, 15], [17, 18, 19, 20], [22, 23, 24, 25]]) 

b. 20  

c.array([[ 2], [ 7], [12]]) 

d.array([21, 22, 23, 24, 25]) 

e.array([[16, 17, 18, 19, 20], [21, 22, 23, 24, 25]]) 

13. Get sum of all values in matrix 

14. Get sum of all the columns in matrix 

15. Get Standard deviation , varience , minimum, maximum from matrix row wise. 

16. Create 2 d matrix with all border values nan.

In [500]:
1.
import numpy as np

In [411]:
2.
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [413]:
3.
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [415]:
4.
np.arange(10,51)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [417]:
5.
np.arange(10,51,2)

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [419]:
6.
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [421]:
7.
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [423]:
8.
np.random.random(1)

array([0.87838777])

In [425]:
9.
np.random.randn(25)

array([-1.81846097,  0.04409564, -0.97465779, -0.02926223, -0.35855505,
        0.96811154, -1.63461927, -0.87659244, -0.49607977,  0.33010694,
        0.90086491,  0.30946369, -0.12772354,  0.27872136, -2.02471504,
        0.84327545, -0.51601862,  0.46429924, -0.06238207, -0.09815837,
        0.11997086,  1.2499225 ,  0.69712421, -0.15281952,  1.04371769])

In [427]:
10.
np.linspace(0.01,1,100)

array([0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 , 0.11,
       0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 , 0.21, 0.22,
       0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 , 0.31, 0.32, 0.33,
       0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 , 0.41, 0.42, 0.43, 0.44,
       0.45, 0.46, 0.47, 0.48, 0.49, 0.5 , 0.51, 0.52, 0.53, 0.54, 0.55,
       0.56, 0.57, 0.58, 0.59, 0.6 , 0.61, 0.62, 0.63, 0.64, 0.65, 0.66,
       0.67, 0.68, 0.69, 0.7 , 0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77,
       0.78, 0.79, 0.8 , 0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88,
       0.89, 0.9 , 0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99,
       1.  ])

In [429]:
11.
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [463]:
12.
s=np.arange(1,26).reshape(5,5)
s

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [465]:
12.
s[2:,1:]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [467]:
12.
s[3,4]

20

In [469]:
12.
s[0:3,1:2]

array([[ 2],
       [ 7],
       [12]])

In [471]:
12.
s[4]

array([21, 22, 23, 24, 25])

In [481]:
12.
s[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [477]:
13.
np.sum(s)

325

In [479]:
14.
np.sum(s,axis=0)

array([55, 60, 65, 70, 75])

In [485]:
15.
std= np.std(s, axis=1)
var= np.var(s, axis=1)
min= np.min(s, axis=1)
max= np.max(s, axis=1)

display(std,var,min,max)

array([1.41421356, 1.41421356, 1.41421356, 1.41421356, 1.41421356])

array([2., 2., 2., 2., 2.])

array([ 1,  6, 11, 16, 21])

array([ 5, 10, 15, 20, 25])

In [489]:
16.
import numpy as np

rows, cols = 5, 5

S= np.zeros((rows, cols))

S[0, :] = np.nan  
S[-1, :] = np.nan
S[:, 0] = np.nan
S[:, -1] = np.nan

display(S)


array([[nan, nan, nan, nan, nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan,  0.,  0.,  0., nan],
       [nan, nan, nan, nan, nan]])

# Assignment 2

1. Create 1-D, 2-D and 3-D numpy array 

2. Print data type of array. 

3. Print shape and dimensions of all the three different array. 

4. Create another 1-D array of 12 elements filled with zero 

5. Create another 2-D array elements filled with ones. 

6. Create a 1-D array known as Maths Marks out of 100 having 20 elements. 

7. Sort the above array in ascending and descending order. 

8. Create a copy of sorted array to another variable by deep copying. 

9. Create 2-D array of 5x5 which is an identity matrix and then convert 1D. 

10. Create 2-D array of 3x3. Add one more row to it. 

11. Split above array created vertically and horizontally. 
    
12. Create 4x4 identity matrix. Add 4 to each element. 

13. Create 1-D array. Initialize with floating point values. Display its ceil, 

    floor and round (with 2 decimal’s). 

    14. Create 5x5 matrix. Display min, max, variance and standard deviation column-wise. 

15. Create a null vector of size 10 with 6th value filled with 200. 

16. Create a 1-D Array/Vector with values ranging from 100 to 150 in sequence. 

17. Reverse the above vector. 

18. Create a 5x5 matrix with values ranging from 0-24 using some function. 

19. Find indices of nonzero elements from [1,0,2,0,0,4,0,8] 

20. Create a 10x10 matrix with 1 on the borders and 0 inside. 

21. Create 8x8 matrix and fill with 1 and 0 in checkerboard pattern. 

22. Create two 3x3 matrix with random integer values. Perform matrix 

addition, multiplication and subtraction

In [13]:
import numpy as np

In [15]:
1.
a=np.arange(4)
b=np.arange(4).reshape(2,2)
c=np.arange(8).reshape(2,2,2)

display(a,b,c)

array([0, 1, 2, 3])

array([[0, 1],
       [2, 3]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [19]:
2.
c.dtype

dtype('int32')

In [21]:
3.
display(a,a.shape,a.ndim)
display(b,b.shape,b.ndim)
display(c,c.shape,c.ndim)

array([0, 1, 2, 3])

(4,)

1

array([[0, 1],
       [2, 3]])

(2, 2)

2

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

(2, 2, 2)

3

In [23]:
4.
np.zeros(12)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [25]:
5.
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [27]:
6.
d=np.random.randint(0, 101, 20)
display(d)

array([ 29,  41,  15,  32,  11,  57,  55,  18,  31,  48,  76,  50,  87,
       100,  36,  40,  39,  50,  94,  22])

In [29]:
7.
d1=np.sort(d)
d2=np.sort(d)[::-1]
display(d1,d2)

array([ 11,  15,  18,  22,  29,  31,  32,  36,  39,  40,  41,  48,  50,
        50,  55,  57,  76,  87,  94, 100])

array([100,  94,  87,  76,  57,  55,  50,  50,  48,  41,  40,  39,  36,
        32,  31,  29,  22,  18,  15,  11])

In [37]:
8.
display(c)
np.sort(c)
s1=c.copy()
s1[0]=55
display(s1,c)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

array([[[55, 55],
        [55, 55]],

       [[ 4,  5],
        [ 6,  7]]])

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [41]:
9.
e=np.eye(5)
f=e.flatten()
display(e,f)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

array([1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 1.])

In [43]:
10.
e1=np.arange(1,10).reshape(3,3)
e2=np.arange(10,13).reshape(1,3)
e3=np.concatenate((e1,e2), axis=0)
display(e1,e2,e3)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

array([[10, 11, 12]])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [45]:
11.
g=np.vsplit(e3,2)
h=np.hsplit(e3,3)
display(g,h)

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]])]

[array([[ 1],
        [ 4],
        [ 7],
        [10]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12]])]

In [51]:
12.
i=np.eye(4)
i2=i+4
display(i,i2)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

array([[5., 4., 4., 4.],
       [4., 5., 4., 4.],
       [4., 4., 5., 4.],
       [4., 4., 4., 5.]])

In [53]:
13.
j=np.array([-1.23,2.34,3.45,-4.56])
k=np.ceil(j)
l=np.floor(j)
m=np.round(j, 2)
display(j,k,l,m)

array([-1.23,  2.34,  3.45, -4.56])

array([-1.,  3.,  4., -4.])

array([-2.,  2.,  3., -5.])

array([-1.23,  2.34,  3.45, -4.56])

In [55]:
14.
n=np.arange(5,30).reshape(5,5)
min=np.min(n,axis=0)
max=np.max(n,axis=0)
var=np.var(n,axis=0)
std=np.std(n,axis=0)
display(n,min,max,var,std)


array([[ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29]])

array([5, 6, 7, 8, 9])

array([25, 26, 27, 28, 29])

array([50., 50., 50., 50., 50.])

array([7.07106781, 7.07106781, 7.07106781, 7.07106781, 7.07106781])

In [59]:
15.
o=np.zeros(10)
o[5]=200
display(o)

array([  0.,   0.,   0.,   0.,   0., 200.,   0.,   0.,   0.,   0.])

In [61]:
16.
p=np.arange(100,151)
display(p)

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
       113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
       126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
       139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150])

In [63]:
17.
q=d[::-1]
display(q)

array([ 22,  94,  50,  39,  40,  36, 100,  87,  50,  76,  48,  31,  18,
        55,  57,  11,  32,  15,  41,  29])

In [65]:
18.
r=np.array([1,0,2,0,0,4,0,8])
s=np.nonzero(r)[0]
display(r,s)

array([1, 0, 2, 0, 0, 4, 0, 8])

array([0, 2, 5, 7], dtype=int64)

In [67]:
19.
mat=np.zeros((10,10),dtype=int)
mat[0,:]=1
mat[-1,:]=1
mat[:,0]=1
mat[:,-1]=1
display(mat)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [69]:
20.
t=np.zeros((8,8),dtype=int)
t[1::2,::2]=1
t[::2,1::2]=1
display(t)

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [75]:
21.
matrix = np.zeros((8, 8), dtype=int)
matrix[1::2, ::2] = 1
matrix[::2, 1::2] = 1
print(matrix)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [77]:
22.
u1=np.random.randint(1,10, size=(3, 3))
u2=np.random.randint(1,10, size=(3, 3))
add=u1 + u2
mul=np.dot(u1,u2)
sub=u1 - u2
display(u1,u2,add,mul,sub)

array([[7, 8, 4],
       [2, 4, 3],
       [4, 4, 8]])

array([[2, 2, 8],
       [5, 3, 6],
       [5, 1, 6]])

array([[ 9, 10, 12],
       [ 7,  7,  9],
       [ 9,  5, 14]])

array([[ 74,  42, 128],
       [ 39,  19,  58],
       [ 68,  28, 104]])

array([[ 5,  6, -4],
       [-3,  1, -3],
       [-1,  3,  2]])